#!/usr/bin/env bash
# Build the app-logic components for the Cloudflare app runtime (ADR-0002):
#
#   1. cargo-build the wasm32-wasip2 components — the SAME notes/nutrition
#      components tangram-host runs, plus mcp-core (tangram-core's sans-io
#      MCP machine behind the tangram:mcp world);
#   2. jco-transpile each into dist/components/<name>/ (JS glue + core wasm
#      modules; apps get JSPI so the guest's synchronous http-fetch import
#      can suspend on the Worker's async fetch());
#   3. generate dist/components/<name>/cores.js — the loader the Worker
#      imports, wiring the wrangler-compiled WebAssembly.Module imports into
#      jco's instantiate() (workerd forbids runtime WebAssembly.compile, so
#      modules must arrive pre-compiled through the bundler).
#
# Run from anywhere: paths are derived from this script's location. Output
# is deterministic for a given source tree; dist/ is gitignored.
# Needs: cargo with the wasm32-wasip2 target, node/npm (npm ci already run
# in this directory so node_modules/.bin/jco exists).

set -euo pipefail

CF_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$CF_DIR/../.." && pwd)
JCO="$CF_DIR/node_modules/.bin/jco"
OUT="$CF_DIR/dist/components"

[[ -x $JCO ]] || {
    echo "error: $JCO not found — run 'npm ci' in cloud/cloudflare first" >&2
    exit 1
}

echo "[components] building wasm32-wasip2 components (cargo)…"
cargo build -p tangram-notes -p tangram-nutrition --lib \
    --target wasm32-wasip2 --release --quiet \
    --manifest-path "$REPO_ROOT/Cargo.toml"
cargo build --target wasm32-wasip2 --release --quiet \
    --manifest-path "$CF_DIR/mcp-core/Cargo.toml"

# transpile <component.wasm> <name> [extra jco flags…]
transpile() {
    local wasm=$1 name=$2
    shift 2
    rm -rf "$OUT/$name"
    "$JCO" transpile "$wasm" -o "$OUT/$name" --name "$name" \
        --instantiation async --no-namespaced-exports --quiet "$@"

    # The generated loader: imports every core wasm module (wrangler bundles
    # them as pre-compiled WebAssembly.Module) and adapts them to jco's
    # getCoreModule callback.
    {
        echo "// generated by build-components.sh — do not edit"
        echo "import { instantiate } from './$name.js';"
        local i=0 base
        for core in "$OUT/$name/$name".core*.wasm; do
            base=$(basename "$core")
            echo "import core$i from './$base';"
            i=$((i + 1))
        done
        echo "const cores = {"
        i=0
        for core in "$OUT/$name/$name".core*.wasm; do
            base=$(basename "$core")
            echo "  '$base': core$i,"
            i=$((i + 1))
        done
        echo "};"
        echo "export function load(imports) {"
        echo "  return instantiate((name) => cores[name], imports);"
        echo "}"
    } >"$OUT/$name/cores.js"
    cat >"$OUT/$name/cores.d.ts" <<'EOF'
// generated by build-components.sh — do not edit
// Loose typing on purpose: the precise jco types use versioned WASI import
// keys while the runtime lookup is unversioned; the Worker narrows the
// result to its own interfaces (src/components.ts, src/mcp.ts).
export function load(
  imports: Record<string, Record<string, unknown>>
): Promise<Record<string, unknown>>;
EOF
    echo "[components] $name -> dist/components/$name ($(du -sh "$OUT/$name" | cut -f1))"
}

# Apps: JSPI lets the guest's synchronous http-fetch import await fetch();
# the dispatch export (the only one that can suspend) becomes a Promise.
JSPI_FLAGS=(--async-mode jspi
    --async-imports 'tangram:app/host#http-fetch'
    --async-exports 'tangram:app/guest#dispatch')
transpile "$REPO_ROOT/target/wasm32-wasip2/release/notes.wasm" notes "${JSPI_FLAGS[@]}"
transpile "$REPO_ROOT/target/wasm32-wasip2/release/nutrition.wasm" nutrition "${JSPI_FLAGS[@]}"
# The MCP machine is pure protocol — fully synchronous, no JSPI.
transpile "$CF_DIR/mcp-core/target/wasm32-wasip2/release/tangram_mcp_core.wasm" mcp

echo "[components] done"
