// The inline `/<name>` agent/skill RUN popup (P1). Triggered from the vault
// editor when the caret sits right after a `/<name>` that resolves to a saved
// definition and the user presses Enter (or clicks a highlighted token — see
// editor.ts / slashTrigger.ts). It mirrors modal.ts's overlay/dialog visual
// language (a single-instance overlay at the shell root, keyboard-first,
// backdrop-click / Esc to dismiss).
//
// Single-turn only: the prompt the user types is sent to DeepSeek via the
// host's `/llm/deepseek` proxy (relative path `../llm/deepseek/...` — the shell
// is mounted at `/tangram/`, so it resolves to the host's proxy; the host
// injects the API key, never the browser). The call is BOUND to the def: its
// `model` is passed through and its `instructions` become the system message.
// The response is shown as a chat exchange, then the user can Save (replace the
// `/<name>` token with an indented blockquote of the prompt + response) or Exit
// (discard, leave the token untouched).
//
// The CREATE/DEFINE popup (`/agent`) lives below — see openCreateAgentPopup.
//
// Scope guard (P1): DeepSeek route only (the model string is passed through but
// provider routing is later), single prompt → response, exactly this flow. No
// multi-turn, no provider choice, no tools/sandbox.

import { DEFAULT_MODEL, type AgentDef } from "./agents";

/** What the popup does with the exchange when the user chooses Save. */
export interface AgentPopupCallbacks {
  /** Replace the triggering `/<name>` range with the given markdown block and
   *  refocus the editor. Wired by main.ts onto the live MdEditor. */
  onSave: (block: string) => void;
  /** Close with no document change (Exit / dismiss); refocus the editor. */
  onClose: () => void;
}

// Only one popup at a time (like promptName/confirmAction). Re-opening while one
// is up closes the previous instance first.
let current: { dismiss: () => void } | null = null;

/** True while the run popup is open (used by the editor's auto-open guard). */
export function isAgentPopupOpen(): boolean {
  return current !== null;
}

/** Format the prompt + response as a markdown blockquote block (each line
 *  prefixed with `> `), with a trailing provenance line backlinking the
 *  skill/agent + model that generated it (Fix 3), e.g.
 *    > Input: <prompt>
 *    > Output: <line 1 of response>
 *    > <line 2 of response>
 *    > ↳ generated by /<name> · model: <model>
 *
 *  Multi-line responses keep every line inside the quote so live-preview
 *  renders one clean indented block. The `/<name>` stays a live reference (the
 *  highlighter re-chips it; Enter/click re-run it). The provenance line is
 *  built from ` · `-joined segments so a `· version: x.y.z` segment can be
 *  appended later (once agents are versioned) without reformatting. */
export function formatAgentBlock(
  prompt: string,
  response: string,
  name: string,
  model: string,
): string {
  const quote = (text: string) =>
    text
      .split("\n")
      .map((line) => `> ${line}`)
      .join("\n");
  const promptLines = quote(`Input: ${prompt}`);
  const lines = response.split("\n");
  const first = `> Output: ${lines[0] ?? ""}`;
  const rest = lines.slice(1).map((line) => `> ${line}`);
  // Forward-compatible provenance: ` · `-joined segments, so `version: x.y.z`
  // (or other metadata) can be appended later without reformatting the line.
  const segments = [`generated by /${name}`, `model: ${model}`];
  const provenance = `> ↳ ${segments.join(" · ")}`;
  return [promptLines, first, ...rest, provenance].join("\n");
}

interface DeepSeekResponse {
  choices?: Array<{ message?: { content?: string } }>;
}

// POST the prompt to DeepSeek through the host proxy. The shell is mounted at
// `/tangram/`, so the RELATIVE path `../llm/deepseek/...` resolves to the host's
// `/llm/deepseek` proxy. No API key here — the host injects it. The call is
// bound to the def: `model` is passed through and `instructions` (if any) ride
// as the system message ahead of the user's prompt. (P1 always uses the
// `/llm/deepseek` route; provider routing by model is later.)
async function callDeepSeek(
  prompt: string,
  model: string,
  instructions: string,
): Promise<string> {
  const messages: Array<{ role: string; content: string }> = [];
  if (instructions.trim().length > 0) {
    messages.push({ role: "system", content: instructions });
  }
  messages.push({ role: "user", content: prompt });
  const res = await fetch("../llm/deepseek/v1/chat/completions", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      model: model || DEFAULT_MODEL,
      messages,
    }),
  });
  if (!res.ok) {
    let detail = "";
    try {
      detail = (await res.text()).slice(0, 300);
    } catch {
      /* ignore */
    }
    throw new Error(`LLM request failed (${res.status})${detail ? `: ${detail}` : ""}`);
  }
  const json = (await res.json()) as DeepSeekResponse;
  const content = json.choices?.[0]?.message?.content;
  if (typeof content !== "string" || content.length === 0) {
    throw new Error("LLM returned an empty response");
  }
  return content;
}

/**
 * Open the `/<name>` RUN popup, bound to the resolved `def`. Single-instance:
 * any open popup is dismissed first. The popup walks Prompt → Waiting → Chat
 * (with Save/Exit) or Error (Retry); the title reads "Running: <name>".
 * Backdrop click / Esc dismiss at any state via `callbacks.onClose`.
 */
export function openAgentPopup(def: AgentDef, callbacks: AgentPopupCallbacks): void {
  current?.dismiss();

  const runTitle = `Running: ${def.name}`;

  const overlay = document.createElement("div");
  overlay.className = "modal-overlay";

  const dialog = document.createElement("div");
  dialog.className = "modal agent-popup";
  dialog.setAttribute("role", "dialog");
  dialog.setAttribute("aria-modal", "true");
  overlay.appendChild(dialog);

  let settled = false;
  function teardown() {
    if (settled) return;
    settled = true;
    document.removeEventListener("keydown", onKey, true);
    overlay.remove();
    if (current?.dismiss === dismiss) current = null;
  }
  // Dismiss = close with no document change (return to editor, @agent stays).
  function dismiss() {
    if (settled) return;
    teardown();
    callbacks.onClose();
  }
  current = { dismiss };

  function onKey(e: KeyboardEvent) {
    if (e.key === "Escape") {
      e.preventDefault();
      e.stopPropagation();
      dismiss();
    }
  }
  document.addEventListener("keydown", onKey, true);
  // Backdrop click (outside the dialog) dismisses, like the naming modal.
  overlay.addEventListener("mousedown", (e) => {
    if (e.target === overlay) dismiss();
  });

  // ── Prompt state ──────────────────────────────────────────────────────────
  function renderPrompt(initial = "") {
    dialog.replaceChildren();

    const title = document.createElement("div");
    title.className = "modal-title";
    title.textContent = runTitle;

    const input = document.createElement("textarea");
    input.className = "modal-input agent-input";
    input.rows = 3;
    input.placeholder = `What should ${def.name} do?`;
    input.value = initial;
    input.spellcheck = false;

    const actions = document.createElement("div");
    actions.className = "modal-actions";
    const submitBtn = document.createElement("button");
    submitBtn.type = "button";
    submitBtn.className = "modal-btn primary";
    submitBtn.textContent = "Submit";
    actions.append(submitBtn);

    dialog.append(title, input, actions);

    function refresh() {
      submitBtn.disabled = input.value.trim().length === 0;
    }
    function submit() {
      const prompt = input.value.trim();
      if (!prompt) return;
      void runPrompt(prompt);
    }

    input.addEventListener("input", refresh);
    // Enter submits (Shift+Enter inserts a newline in the textarea).
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        submit();
      }
    });
    submitBtn.addEventListener("click", submit);

    refresh();
    input.focus();
  }

  // ── Waiting state ───────────────────────────────────────────────────────────
  function renderWaiting(prompt: string) {
    dialog.replaceChildren();
    const title = document.createElement("div");
    title.className = "modal-title";
    title.textContent = runTitle;

    const chat = document.createElement("div");
    chat.className = "agent-chat";
    chat.appendChild(bubble("user", prompt));

    const thinking = document.createElement("div");
    thinking.className = "agent-thinking";
    const spinner = document.createElement("span");
    spinner.className = "agent-spinner";
    thinking.append(spinner, document.createTextNode("thinking…"));
    chat.appendChild(thinking);

    dialog.append(title, chat);
  }

  // ── Chat (result) state: prompt + response bubbles, then Save / Exit ────────
  function renderChat(prompt: string, response: string) {
    dialog.replaceChildren();
    const title = document.createElement("div");
    title.className = "modal-title";
    title.textContent = runTitle;

    const chat = document.createElement("div");
    chat.className = "agent-chat";
    chat.appendChild(bubble("user", prompt));
    chat.appendChild(bubble("assistant", response));

    const actions = document.createElement("div");
    actions.className = "modal-actions";
    const exitBtn = document.createElement("button");
    exitBtn.type = "button";
    exitBtn.className = "modal-btn";
    exitBtn.textContent = "Exit";
    const saveBtn = document.createElement("button");
    saveBtn.type = "button";
    saveBtn.className = "modal-btn primary";
    saveBtn.textContent = "Save";
    actions.append(exitBtn, saveBtn);

    dialog.append(title, chat, actions);

    // Exit: discard the response, leave the original `/<name>` untouched.
    exitBtn.addEventListener("click", () => dismiss());
    // Save: replace `/<name>` with the indented prompt+response blockquote,
    // backlinking the def's name + model that generated it (Fix 3).
    saveBtn.addEventListener("click", () => {
      teardown();
      callbacks.onSave(formatAgentBlock(prompt, response, def.name, def.model));
    });
    saveBtn.focus();
  }

  // ── Error state: message + Retry / Cancel ───────────────────────────────────
  function renderError(prompt: string, message: string) {
    dialog.replaceChildren();
    const title = document.createElement("div");
    title.className = "modal-title";
    title.textContent = runTitle;

    const chat = document.createElement("div");
    chat.className = "agent-chat";
    chat.appendChild(bubble("user", prompt));

    const err = document.createElement("div");
    err.className = "agent-error";
    err.textContent = message;
    chat.appendChild(err);

    const actions = document.createElement("div");
    actions.className = "modal-actions";
    const cancelBtn = document.createElement("button");
    cancelBtn.type = "button";
    cancelBtn.className = "modal-btn";
    cancelBtn.textContent = "Cancel";
    const retryBtn = document.createElement("button");
    retryBtn.type = "button";
    retryBtn.className = "modal-btn primary";
    retryBtn.textContent = "Retry";
    actions.append(cancelBtn, retryBtn);

    dialog.append(title, chat, actions);

    cancelBtn.addEventListener("click", () => dismiss());
    // Retry goes back to the prompt state, preserving the typed prompt.
    retryBtn.addEventListener("click", () => renderPrompt(prompt));
    retryBtn.focus();
  }

  async function runPrompt(prompt: string) {
    renderWaiting(prompt);
    try {
      const response = await callDeepSeek(prompt, def.model, def.instructions);
      if (settled) return;
      renderChat(prompt, response);
    } catch (e) {
      if (settled) return;
      renderError(prompt, e instanceof Error ? e.message : String(e));
    }
  }

  document.body.appendChild(overlay);
  renderPrompt();
}

function bubble(role: "user" | "assistant", text: string): HTMLElement {
  const wrap = document.createElement("div");
  wrap.className = `agent-bubble ${role}`;
  const who = document.createElement("div");
  who.className = "agent-bubble-role micro";
  who.textContent = role === "user" ? "You" : "Agent";
  const body = document.createElement("div");
  body.className = "agent-bubble-text";
  body.textContent = text;
  wrap.append(who, body);
  return wrap;
}
